#ifndef CONFIG_H
#define CONFIG_H

#include <stdint.h>

#define DISPLAY_WIDTH 128
#define DISPLAY_HEIGHT 128
#define UI_HEIGHT 25

#define JOY_CENTER 2048
#define DEADZONE 5
#define MAX_SPEED 6

#define GAME_START_VALUE 600
#define TARGET_HALF_SIZE 4

#define BUTTON BIT7
#define RESTART_BUTTON BIT0

#define BUZZER BIT5

#define COLOR_WHITE 0xFFFFFFL
#define COLOR_BLACK 0x000000L
#define COLOR_BLUE 0xFF0000L
#define COLOR_RED 0x0000FFL

#endif